### PR TITLE
Add support for aioboto3 9.2.2

### PR DESCRIPTION
**Pull request by andrewleech**
Hi, thanks for this project!
I'm using mandate to handle login with AWSIoTPythonSDK in a project to support a particular home thermostat system in home assistant - https://gitlab.com/alelec/ha_magiqtouch

I've had a lot of difficulties getting dependencies to line up between the various libraries involved, but updating mandate to the current aioboto3 9.2.2 seems to have them all aligned / working for me.

I think the basic chance to use the session object is all that's needed for compatibility, but haven't done particularly extensive testing yet.

### CODE REVIEW

**Comment by errietta** [comment]
Thanks! I will have to check it out later in the week or during the weekend, especially since the CI/CD system I was using (Travis) have decided to drop their support for FOSS so I would currently have no way to release to pip.

**Comment by andrewleech** [comment]
Cheers, no rush. I hadn't realised Travis had become restricted, I'm assuming that's after github brought in actions... what a shame.

I've had a go setting up GitHub actions and added the commit to this branch, seems to be working... 
It can be run manually at the moment ( see build here: https://github.com/andrewleech/mandate/actions/runs/1414506876 ) but once merged should be integrated into merge requests.

It'll need your pypi login added (https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github) before the publish works, but I think it's configured correctly otherwise.

ref:
* https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
* https://dev.to/arnu515/create-a-pypi-pip-package-test-it-and-publish-it-using-github-actions-part-2-1o83

**Comment by andrewleech** [comment]
FYI I'm happy pointing to my fork/branch as the dependency on my project for now so absolutely no pressure to review/merge/release - it's just here if and when you want to look at this next!

**Comment by errietta** [comment]
Thanks, awesome work on getting github actions working too!

**Comment by errietta** [comment]
Thanks, it's published now! https://pypi.org/project/mandate/2.0.1/

**Comment by andrewleech** [comment]
Great, glad I could help thanks!

**Pull request merged**
